### ISSUE TITLE
Migrate the Plugin Documentation of the JPA 2 Plugin to the new Reference Manual

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqa-jpa2-plugin#8]
### Task Description

Migrate the existing documentation of the JPA 2 Plugin to the new reference manul.

### Definition of Done for the Implementers
- [ ] The reference manual contains the same information as the old user manual
- [ ] The section on the JPA 2 Plugin in the old user manual points to the section for the plugin in the reference manual

**Comment by StephanPirnbaum** [comment]
Plugin removed from core distribution with jQA 2.0
